'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import Link from 'next/link'

interface HumorFlavor {
  id: string
  [key: string]: any
}

interface Caption {
  id: string
  content: string
  like_count?: number
  created_datetime_utc?: string
  [key: string]: any
}

export default function CaptionsPage() {
  const supabase = createClient()
  const [flavors, setFlavors] = useState<HumorFlavor[]>([])
  const [selectedFlavorId, setSelectedFlavorId] = useState<string>('all')
  const [captions, setCaptions] = useState<Caption[]>([])
  const [loading, setLoading] = useState(false)
  const [flavorsLoading, setFlavorsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [captionCols, setCaptionCols] = useState<string[]>([])

  // Load all flavors for the selector
  useEffect(() => {
    const fetchFlavors = async () => {
      const { data, error } = await supabase
        .from('humor_flavors')
        .select('*')
        .order('created_datetime_utc', { ascending: false })
      if (error) setError(error.message)
      setFlavors(data ?? [])
      setFlavorsLoading(false)
    }
    fetchFlavors()
  }, [])

  // Load captions when selection changes
  useEffect(() => {
    const fetchCaptions = async () => {
      setLoading(true)
      setError(null)

      let query = supabase
        .from('captions')
        .select('*')
        .order('created_datetime_utc', { ascending: false })
        .limit(100)

      if (selectedFlavorId !== 'all') {
        // Try filtering by humor_flavor_id (may or may not exist)
        query = query.eq('humor_flavor_id', selectedFlavorId)
      }

      const { data, error } = await query

      if (error) {
        // Column might not exist — try without filter and show all
        if (selectedFlavorId !== 'all' && error.message.includes('humor_flavor_id')) {
          const { data: allData, error: allError } = await supabase
            .from('captions')
            .select('*')
            .order('created_datetime_utc', { ascending: false })
            .limit(100)
          if (allError) setError(allError.message)
          else {
            setCaptions(allData ?? [])
            if (allData && allData.length > 0) setCaptionCols(Object.keys(allData[0]))
            setError('Note: captions table may not have a humor_flavor_id column. Showing all captions.')
          }
        } else {
          setError(error.message)
        }
      } else {
        setCaptions(data ?? [])
        if (data && data.length > 0) setCaptionCols(Object.keys(data[0]))
      }

      setLoading(false)
    }

    fetchCaptions()
  }, [selectedFlavorId])

  const SKIP_DISPLAY = ['id', 'profile_id', 'image_id', 'humor_flavor_id', 'created_by_user_id', 'modified_by_user_id']

  const getFlavorDisplayName = (f: HumorFlavor) =>
    f.description ?? f.slug ?? String(f.id)

  return (
    <div className="space-y-8">
      <div>
        <div className="text-[10px] text-[#bbb] dark:text-[#444] tracking-[0.3em] uppercase mb-1">
          Prompt Chain
        </div>
        <h1 className="text-2xl text-[#0a0a0a] dark:text-white tracking-tight">Captions</h1>
        <p className="text-xs text-[#aaa] dark:text-[#555] mt-1">
          Captions generated by humor flavors
        </p>
      </div>

      {/* Filter by flavor */}
      <div className="flex items-center gap-3">
        <label className="text-[10px] text-[#888] dark:text-[#444] tracking-widest uppercase flex-shrink-0">
          Filter by flavor
        </label>
        {flavorsLoading ? (
          <div className="text-[10px] text-[#bbb] dark:text-[#444] tracking-widest uppercase">Loading...</div>
        ) : (
          <select
            value={selectedFlavorId}
            onChange={(e) => setSelectedFlavorId(e.target.value)}
            className="bg-transparent border border-[#ddd] dark:border-[#333] text-[#0a0a0a] dark:text-white text-xs px-3 py-2 focus:outline-none focus:border-[#555] dark:focus:border-[#666] min-w-[220px]"
          >
            <option value="all">All captions</option>
            {flavors.map((f) => (
              <option key={f.id} value={f.id}>
                {getFlavorDisplayName(f)}
              </option>
            ))}
          </select>
        )}
        {selectedFlavorId !== 'all' && (
          <Link
            href={`/humor-flavors/${selectedFlavorId}`}
            className="text-[10px] text-[#aaa] dark:text-[#555] hover:text-[#0a0a0a] dark:hover:text-white tracking-widest uppercase transition-colors"
          >
            Manage Steps →
          </Link>
        )}
      </div>

      {error && (
        <div className="border border-amber-200 dark:border-amber-900 bg-amber-50 dark:bg-amber-950/20 p-3">
          <p className="text-xs text-amber-700 dark:text-amber-400">{error}</p>
        </div>
      )}

      {loading ? (
        <div className="text-[10px] text-[#bbb] dark:text-[#444] tracking-widest uppercase">Loading...</div>
      ) : captions.length === 0 ? (
        <div className="space-y-2">
          <p className="text-xs text-[#aaa] dark:text-[#444]">
            No captions found{selectedFlavorId !== 'all' ? ' for this flavor' : ''}.
          </p>
          {selectedFlavorId !== 'all' && (
            <Link
              href={`/humor-flavors/${selectedFlavorId}`}
              className="text-xs text-blue-600 dark:text-blue-400 hover:underline block"
            >
              Test this flavor to generate captions →
            </Link>
          )}
        </div>
      ) : (
        <div className="space-y-2">
          <div className="text-[10px] text-[#bbb] dark:text-[#444] tracking-widest uppercase mb-3">
            {captions.length} caption{captions.length !== 1 ? 's' : ''}
          </div>
          {captions.map((caption, i) => (
            <div
              key={caption.id ?? i}
              className="border border-[#ececec] dark:border-[#1a1a1a] bg-[#fafafa] dark:bg-[#0f0f0f] p-4"
            >
              {/* Main content */}
              {caption.content && (
                <p className="text-sm text-[#0a0a0a] dark:text-white leading-relaxed mb-2">
                  {caption.content}
                </p>
              )}

              {/* Meta row */}
              <div className="flex items-center gap-4 flex-wrap">
                {caption.like_count !== undefined && caption.like_count !== null && (
                  <span className={`text-xs tabular-nums font-mono ${
                    (caption.like_count ?? 0) > 0
                      ? 'text-green-600 dark:text-green-500'
                      : (caption.like_count ?? 0) < 0
                      ? 'text-red-500 dark:text-red-400'
                      : 'text-[#aaa] dark:text-[#555]'
                  }`}>
                    {(caption.like_count ?? 0) > 0 ? '+' : ''}{caption.like_count}
                  </span>
                )}

                {caption.created_datetime_utc && (
                  <span className="text-[9px] text-[#ccc] dark:text-[#444]">
                    {new Date(caption.created_datetime_utc).toLocaleString()}
                  </span>
                )}

                {caption.humor_flavor_id && selectedFlavorId === 'all' && (
                  <span className="text-[9px] text-[#bbb] dark:text-[#444]">
                    Flavor: {(() => { const f = flavors.find((f) => f.id === caption.humor_flavor_id); return f ? getFlavorDisplayName(f) : String(caption.humor_flavor_id) })()}
                  </span>
                )}

                {/* Extra columns */}
                {captionCols
                  .filter((c) => !['id', 'content', 'like_count', 'created_at', 'updated_at', 'created_datetime_utc', 'modified_datetime_utc', 'profile_id', 'image_id', 'humor_flavor_id', 'created_by_user_id', 'modified_by_user_id'].includes(c))
                  .map((col) =>
                    caption[col] !== null && caption[col] !== undefined ? (
                      <span key={col} className="text-[9px] text-[#bbb] dark:text-[#444]">
                        {col}: {String(caption[col])}
                      </span>
                    ) : null
                  )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
